name: Weekly Market Insights Report

on:
  schedule:
    - cron: '0 13 * * 1'  # Every Monday at 8 AM EST (13:00 UTC)
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  send-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run weekly report
      env:
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python weekly_news_agent.py
